### ISSUE TITLE
Implement Recipes Recommendation System

### ISSUE THREAD

**Issue by claryng** [mya03/Meal-Planner#29]
## Tasks
- [x] #30
- [x] #36
- [x] #37
- [x] #39
- [x] #49
- [x] #42
- [x] #38
- [x] #43
- [x] #50
- [x] #47
- [x] #60
- [x] #64

**Comment by mya03** [comment]
Looks good!

**Comment by claryng** [comment]
Thanks, I will take on this issue then!
