### ISSUE TITLE
Front-end Integration for Recommending Recipe in Goal-oriented Meal Planner feature

### ISSUE THREAD

**Issue by eris0k** [mya03/Meal-Planner#50]
## Description
Front-end integration:
- In GoalOrientedMealPlanner, calculate average calories for each meal based on the TDEE
- Use that calories and the function implemented in #49 to get 3 recipes for breakfast, lunch, and dinner
- Display the recipes in MealPlanner page

**Comment by claryng** [comment]
Done and merge into implement-recipes-recommendation-system branch
